# Change these first
owner: ForestCraftMC # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: LittleSkin 用户中心
    url: https://littleskin.cn/user
    expectedStatusCodes: [ 200, 201, 400, 401, 403, 404 ]
  - name: LittleSkin 认证 API
    url: https://littleskin.cn/api/yggdrasil
    expectedStatusCodes: [ 200, 201, 400, 401, 403, 404 ]
  - name: Forest Craft 服务器
    url: $FC_ADDRESS
  - name: OpenFrp Tunnel 1
    url: $FC_TN1
    port: 55234
    check: "tcp-ping"
  - name: OpenFrp Tunnel 2
    url: $FC_TN2
    port: 55123
    check: "tcp-ping"
  - name: OpenFrp Tunnel 3
    url: $FC_TN3
    port: 55123
    check: "tcp-ping"
  - name: Cloudflare Public DNS
    url: https://1.1.1.1/dns-query
    expectedStatusCodes: [ 200, 201, 400, 401, 403, 404 ]

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: fcstatus.nijika.in
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - Forest Craft
  introTitle: "**Forest Craft** 的状态监视页"
  introMessage: 如果 LittleSkin 和 OpenFrp Tunnels 都不是全红，那大概是你自己炸了而不是服务器炸了
  navbar:
    - title: 主页
      href: https://fc.nijika.in
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
